spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/cqgzcstc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://154.12.39.93:3306/cqgzcstc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://1Panel-mysql-5QiT:3306/cqgzcstc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 700113
    username: cqgzcstc
    password: EnDMFFcGhbAaX2bA
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    hikari:
      initializationFailTimeout: 20
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  web:
    resources:
      static-locations: classpath:/static/
  application:
    name: CqgzCSTC

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chasexi.cqgzcstc.entity
  configuration:
    map-underscore-to-camel-case: true
#  configuration:
#   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080